// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkifvejipuyoxwuneljl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtraWZ2ZWppcHV5b3h3dW5lbGpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMyOTI5NzgsImV4cCI6MjA3ODg2ODk3OH0.tCs1WE2kx3HKMmInLu-lcM2gVBO4cbGChM8cy2jZLlM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});